// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/internal/sensor/repository.go
//
// Generated by this command:
//
//	mockgen -source=./app/internal/sensor/repository.go -destination=./app/internal/sensor/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sensor "github.com/anoop-dryad/bridgehead/app/internal/sensor"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// DeleteSensorByEui mocks base method.
func (m *MockRepositoryInterface) DeleteSensorByEui(tx context.Context, sensorEUI string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSensorByEui", tx, sensorEUI)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSensorByEui indicates an expected call of DeleteSensorByEui.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteSensorByEui(tx, sensorEUI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSensorByEui", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteSensorByEui), tx, sensorEUI)
}

// GetByEUI mocks base method.
func (m *MockRepositoryInterface) GetByEUI(ctx context.Context, eui string) (*sensor.Sensor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEUI", ctx, eui)
	ret0, _ := ret[0].(*sensor.Sensor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEUI indicates an expected call of GetByEUI.
func (mr *MockRepositoryInterfaceMockRecorder) GetByEUI(ctx, eui any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEUI", reflect.TypeOf((*MockRepositoryInterface)(nil).GetByEUI), ctx, eui)
}

// GetMappingBySensorEUI mocks base method.
func (m *MockRepositoryInterface) GetMappingBySensorEUI(ctx context.Context, sensorEUI string) (*sensor.GatewayMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMappingBySensorEUI", ctx, sensorEUI)
	ret0, _ := ret[0].(*sensor.GatewayMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMappingBySensorEUI indicates an expected call of GetMappingBySensorEUI.
func (mr *MockRepositoryInterfaceMockRecorder) GetMappingBySensorEUI(ctx, sensorEUI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMappingBySensorEUI", reflect.TypeOf((*MockRepositoryInterface)(nil).GetMappingBySensorEUI), ctx, sensorEUI)
}

// GetSensorsByGatewayEUI mocks base method.
func (m *MockRepositoryInterface) GetSensorsByGatewayEUI(ctx context.Context, gatewayEUI string) ([]*sensor.Sensor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSensorsByGatewayEUI", ctx, gatewayEUI)
	ret0, _ := ret[0].([]*sensor.Sensor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSensorsByGatewayEUI indicates an expected call of GetSensorsByGatewayEUI.
func (mr *MockRepositoryInterfaceMockRecorder) GetSensorsByGatewayEUI(ctx, gatewayEUI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSensorsByGatewayEUI", reflect.TypeOf((*MockRepositoryInterface)(nil).GetSensorsByGatewayEUI), ctx, gatewayEUI)
}

// UpsertMapping mocks base method.
func (m_2 *MockRepositoryInterface) UpsertMapping(ctx context.Context, m sensor.GatewayMapping) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpsertMapping", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertMapping indicates an expected call of UpsertMapping.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertMapping(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertMapping", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertMapping), ctx, m)
}

// UpsertSensor mocks base method.
func (m *MockRepositoryInterface) UpsertSensor(ctx context.Context, s sensor.Sensor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSensor", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertSensor indicates an expected call of UpsertSensor.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertSensor(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSensor", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertSensor), ctx, s)
}

// WithTransaction mocks base method.
func (m *MockRepositoryInterface) WithTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockRepositoryInterfaceMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepositoryInterface)(nil).WithTransaction), ctx, fn)
}
